### ISSUE TITLE
Can't work out how to use this script

### ISSUE THREAD

**Issue by Yimyai** [giveabit/Trio-Plus-Data#1]
![trio script](https://cloud.githubusercontent.com/assets/27401332/24991589/22fbbdc0-2046-11e7-9f8f-f073df853071.JPG)
I have downloaded python and the script and placed the script in the folder where my Trio+ songs are located. I then run the script. It opens a DOS style window as per the attached I enter [m] and press Enter and nothing happens. What am I doing wrong?

It will be a really cool tool if it works

**Comment by giveabit** [comment]
Hi,
if you do really start the 'The_Trio+_Tool.py' script from the same location where the .tlsd files are located and choose 'm' then a file list should appear to choose a file to manipulate.
If NO .tlsd files are present within this folder, an error message should come up.
Please do check your settings in the /resource_files/program_defaults.ini and set 'Path to .tlsd files' to '0' (i.e. zero).
Please let me know if the problem persists.
Thanks!!!

**Comment by Yimyai** [comment]
Hi Peter,

 

Thanks for your reply. I have attached a screenshot of the folder with the TLSD files and the script in the same folder. When I double click on the script 



The following window opens. When I select “m” the window closes.



 

Here is a screenshot of the settings



 

Many thanks & best regards

Paul

**Comment by giveabit** [comment]
Paul,
unfortunately I do not see the embedded pictures here on GitHub. Could you please send me an email with the pictures attached?

From what you wrote I guess the script simply crashes after hittig 'm'. Does it, on the other hand, export audio as expected (option 'e')?

And just to make sure - you are using the lastest release v 0.73 from April, 4th?

Thanks a lot and Cheers!

**Comment by giveabit** [comment]
...not hearing anything from you - can we consider this issue solved and close???

Thanks and best regards.

**Comment by giveabit** [comment]
...considered closed!
